import { CopyAll, GitHub, LinkOff } from "@mui/icons-material";

export const data = [
  {
    skillImg: [
      { src: "/react.svg", title: "React" },
      { src: "/redux.svg", title: "Redux" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/css.svg", title: "CSS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/ecommerce.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "E-ecommerce",
    link: "http://e-ecommerce.surge.sh",
  },
  {
    skillImg: [
      { src: "/redux.svg", title: "Redux" },
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/shoppincart.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "E-ecommerce",
    link: "https://shopping-cart77.netlify.app/",
  },
  {
    skillImg: [
      { src: "/mongodb.png", title: "MongoDB" },
      { src: "/node.png", title: "Node" },
      { src: "/Material.png", title: "Material" },
      { src: "/redux.svg", title: "Redux" },
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/css.svg", title: "CSS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/Orico-ecommerce.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Orico-Ecommerce",
    link: "https://orico-ecommerce.netlify.app/",
  },
  {
    skillImg: [
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/css.svg", title: "CSS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/portfolio1.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "My Portfolio",
    link: "https://elbarody.surge.sh/",
  },
  {
    skillImg: [
      { src: "/mongodb.png", title: "MongoDB" },
      { src: "/node.png", title: "Node" },
      { src: "/Material.png", title: "Material" },
      { src: "/redux.svg", title: "Redux" },
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/css.svg", title: "CSS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/orico-social.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "FaceBook",
    link: "https://orico-social.netlify.app",
  },
  {
    skillImg: [
      { src: "/mongodb.png", title: "MongoDB" },
      { src: "/node.png", title: "Node" },
      { src: "/Material.png", title: "Material" },
      { src: "/redux.svg", title: "Redux" },
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/css.svg", title: "CSS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/orico-chat.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "WhatsApp",
    link: "https://orico-chat.netlify.app",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/css.svg", title: "CSS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/portfolio3.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "My Portfolio",
    link: "https://ebrahimelbarody74.github.io/Portfolio/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/sass-delivery.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Delivery",
    link: "https://ebrahimelbarody74.github.io/sass-delivery/",
  },
  {
    skillImg: [
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/dashboard.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Dashboard",
    link: "http://orico-dashboard.netlify.app",
  },
  {
    skillImg: [
      { src: "/redux.svg", title: "Redux" },
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/shoppincart.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "E-ecommerce",
    link: "https://shopping-cart77.netlify.app/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/tarbawy.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Tarbawy",
    link: "https://tarbawy.circulareg.com/",
  },
  {
    skillImg: [
      { src: "/react.svg", title: "React" },
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/fitClub.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Fit Club",
    link: "https://fit-club.surge.sh/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/Spacial-Design.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Spacial Design",
    link: "https://ebrahimelbarody74.github.io/Spacial-Design/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/SASS-Project.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "SASS Project",
    link: "https://ebrahimelbarody74.github.io/SASS-Project",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/portfolio5.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Portfoilo",
    link: "https://ebrahimelbarody74.github.io/index/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/dashboard2.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Dashboard",
    link: "https://ebrahimelbarody74.github.io/portfoilo-index",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/bootstrap.svg", title: "Bootstrap" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/projects/bootstarp.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Bootstrap",
    link: "https://ebrahimelbarody74.github.io/bootstarp",
  },
];

export const small = [
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/bootstrap.svg", title: "Bootstrap" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/smallProjects/Rosary.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Rosary",
    link: "https://ebrahimelbarody74.github.io/Rosary/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/bootstrap.svg", title: "Bootstrap" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/smallProjects/Tic-Tac-Toe.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Tic-Tac-Toe",
    link: "https://ebrahimelbarody74.github.io/Tic-Tac-Toe/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/bootstrap.svg", title: "Bootstrap" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/smallProjects/Calculator.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Calculator",
    link: "https://ebrahimelbarody74.github.io/Calculator/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/bootstrap.svg", title: "Bootstrap" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/smallProjects/challenge.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Challenge",
    link: "https://ebrahimelbarody74.github.io/challenge/",
  },
  {
    skillImg: [
      { src: "/javascript.svg", title: "JavaScript" },
      { src: "/bootstrap.svg", title: "Bootstrap" },
      { src: "/sass.svg", title: "SASS" },
      { src: "/html5.svg", title: "HTML" },
    ],
    img: "/smallProjects/Memory-Game.png",
    srcicons: [
      { Icon: GitHub, title: "GutHub" },
      { Icon: CopyAll, title: "CopyAll" },
      { Icon: LinkOff, title: "Copy" },
    ],
    name: "Memory-Game",
    link: "https://ebrahimelbarody74.github.io/Memory-Game/",
  },
];
